apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservices
spec:
  replicas: 10
  selector:
    matchLabels:
      app: microservice
  template:
    metadata:
      labels:
        app: microservice
    spec:
      containers:
      - name: microservice
        imagePullPolicy: Never
        image: dummy-microservice:latest
        ports:
        - containerPort: 3000
      

---
apiVersion: v1
kind: Service
metadata:
  name: microservice-service
spec:
  type: NodePort
  selector:
    app: microservice
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30001

